services:
  - type: web
    name: pagepay-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pagepay
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://pagepay-admin.onrender.com,https://pagepay-web.onrender.com,http://localhost:3000
      - key: ADMIN_TOKEN
        value: dev-admin-token
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_WEBHOOK_SECRET
        sync: false
      - key: PUBLIC_BASE_URL
        value: https://pagepay-backend.onrender.com
      - key: ADMOB_APP_ID_ANDROID
        value: ca-app-pub-3898064484524772~6521009021
      - key: ADMOB_APP_ID_IOS
        value: ca-app-pub-3898064484524772~4871553842
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dcr5v9f3c
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: pagepay
    engine: postgres
    version: '15'
    plan: free
