"""Audio narration endpoint for v3 Listen mode.

GET /api/v1/content/audio/{unit_id}.mp3

Returns the pre-rendered TTS audio for a reading unit. Public, no
auth, 30-day cache (same pattern as the image proxy). The audio
files are generated by a batch job (services/tts.py) and stored in
{audio_cache_dir}/units/{unit_id}.mp3.

Gating: the ENDPOINT itself is public (so expo-av can fetch it
without passing JWT headers). The PLAYER in the frontend enforces
the premium gate: unit 1 of any work is free, units 2+ check
`isPremium` before allowing playback. The backend doesn't gate
this endpoint because:
  - The client already has the unit_id (from the slice detail response)
  - The audio is the same content as the text, just a different format
  - Gating here would force the client to proxy through an authed
    fetch, which breaks expo-av's background playback cache

If we ever need to gate audio at the network level (e.g. to stop
hotlinking), add a time-limited signed URL pattern, not JWT auth.
"""

import logging
from pathlib import Path

from fastapi import APIRouter, HTTPException, Path as PathParam
from fastapi.responses import FileResponse

from app.config import settings

logger = logging.getLogger("uvicorn.error")

router = APIRouter(prefix="/content/audio", tags=["content"])


def _audio_cache_dir() -> Path:
    """Return the audio cache root. Creates it if missing."""
    d = Path(settings.audio_cache_dir)
    d.mkdir(parents=True, exist_ok=True)
    return d


def _audio_path_for_unit(unit_id: int) -> Path:
    """Map a unit_id to the on-disk audio file path.

    Must match the path logic in services/tts.py. Two-digit shard
    keeps any one dir under ~10k files.
    """
    shard = f"{unit_id % 100:02d}"
    return _audio_cache_dir() / "units" / shard / f"{unit_id}.mp3"


@router.get("/{unit_id}.mp3")
async def get_unit_audio(unit_id: int = PathParam(..., ge=1)):
    """Serve pre-rendered TTS audio for a reading unit.

    Path:
      unit_id: reading_units.id (positive int)

    Returns:
      200 with audio/mpeg and a 30-day Cache-Control.
      404 if the audio hasn't been generated yet.

    The 404 case happens when:
      - A new unit is added to the catalog but the batch job hasn't
        run yet
      - The audio file was manually deleted
      - The work is premium-only and hasn't been queued for TTS

    The client's Listen mode should handle 404 gracefully (show a
    "Audio not available yet" message and fall back to Read mode).
    """
    path = _audio_path_for_unit(unit_id)
    if not path.exists():
        logger.warning(f"Audio not found for unit {unit_id} (expected: {path})")
        raise HTTPException(status_code=404, detail="Audio not generated for this unit")

    return FileResponse(
        path,
        media_type="audio/mpeg",
        headers={
            "Cache-Control": f"public, max-age={settings.audio_cache_ttl_seconds}",
            # Accept-Ranges lets the client seek without re-downloading
            "Accept-Ranges": "bytes",
        },
    )
